Added check_gcc_config_and_reset_if_necessary function, since the gcc-config not being set correctly (or getting unset after an @world upgrade / depclean) appears to cause quite a lot of hard-to-track-down problems.

diff --git a/buildkernel b/buildkernel
--- a/buildkernel
+++ b/buildkernel
@@ -31,7 +31,8 @@ shopt -s nullglob
 # ********************** variables ********************* 
 PROGNAME="$(basename "${0}")"
 CONFFILE="/etc/${PROGNAME}.conf"
-VERSION="1.0.8"
+VERSION="1.0.9"
+ETCPROFILE="/etc/profile"
 DEFAULTEFIBOOTFILE="bootx64.efi"
 EFIBOOTFILE="${DEFAULTEFIBOOTFILE}"
 NEWVERSION="$(basename $(realpath "/usr/src/linux"))"
@@ -225,6 +226,29 @@ suppress_colour_if_output_not_to_a_terminal() {
 check_file_exists() {
     if [ ! -f "${1}" ]; then
         die "File '${1}' does not exist"
+    fi
+}
+check_gcc_config_and_reset_if_necessary() {
+    # check if gcc-config exists with an error - if it does, then
+    # attempt to set one based on the current gcc version number
+    if ! gcc-config --get-current-profile >/dev/null 2>&1; then
+        # unset or invalid, attempt to force this to the current gcc
+        # version
+        local GCC_VERSION="$(gcc --version | head -n 1 | sed 's/^.* //')"
+        if gcc-config "${GCC_VERSION}"; then
+            warning "gcc configuration was reset"
+            if [ -s "${ETCPROFILE}" ]; then
+                set +e
+                set +u
+                shopt -u nullglob
+                source "${ETCPROFILE}"
+                shopt -s nullglob
+                set -e
+                set -u
+            fi
+        else
+            die "failed to set gcc configuration"
+        fi
     fi
 }
 mount_and_remember() {
@@ -1932,6 +1956,7 @@ source_etc_conf_file
 process_command_line_options "${@}"
 ask_whether_to_proceed
 
+check_gcc_config_and_reset_if_necessary
 if_option_unset "ARG_STAGEONLY" ensure_efi_partition_mounted
 if ((ARG_COPYFROMSTAGING==0)); then    
     enter_build_directory
